<?php
// DB
// define('TABLE_DGF', 'dgf');
// define('TABLE_CONTRAT_PRO', 'dgf_contrat_pro');
// define('TABLE_CONTRAT', 'temp_dgf_form_contrat');
// define('TABLE_FORMATION', 'temp_dgf_form_formation');
// define('TABLE_TUTEUR', 'temp_dgf_form_tuteur');
// define('TABLE_FORM_SALARIE', 'temp_dgf_form_salarie');
// define('TABLE_SALARIE', 'temp_dgf_form_salarie');
// define('TABLE_LIEN_EMPLOYE', 'lien_dgf_ref_esclave_entreprise');
// define('TABLE_REF_DERNIERE_SITUATION', 'ref_derniere_situation');
// define('TABLE_REF_DIPLOME', 'ref_diplome');
// define('TABLE_REF_MIN_SOCIAUX', 'ref_beneficiaire_minimas_sociaux');
// define('TABLE_TYPE_CONTRAT', 'ref_type_contrat');
// define('TABLE_TYPE_CONTRAT_PRO', 'ref_type_contrat_pro');
// define('TABLE_FORM_ORGA_FORMATION', 'temp_dgf_form_organisme_formation');
// define('TABLE_REF_ENTREPRISE', 'lien_dgf_ref_esclave_entreprise');
// define('TABLE_TYPE_CONTRAT_EXTRANET', 'ref_type_contrat');
// define('TABLE_GROUPE', 'ref_groupe');

// define('VUE_ORGA_FORMATION', 'v_organismes_de_formation');
// define('VUE_ENTERPRISES', 'v_entreprises');
// define('VUE_NAFS', 'v_nafs');
// define('VUE_CONVENTION_COLLECTIVE', 'v_conventions_collectives');
// define('VUE_ADRESSE_ENTREPRISE', 'v_adresses_entreprises');
// define('VUE_SALARIE', 'v_salaries');
// define('VUE_SPECIALITE_FORMATION', 'v_specialites_de_formation');
// define('VUE_INTITULES_FORMATION', 'v_intitules_de_formation');

// REFERENCES
define('TEMPLATE_CERFA', 'cerfa_12434_template.pdf');
