<?php
/**
 * @file
 * opcaim_roles.features.user_role.inc
 */

/**
 * Implements hook_user_default_roles().
 */
function opcaim_roles_user_default_roles() {
  $roles = array();

  // Exported role: ADMIN ENTREPRISE.
  $roles['ADMIN ENTREPRISE'] = array(
    'name' => 'ADMIN ENTREPRISE',
    'weight' => 9,
  );

  // Exported role: ADMIN OPCAIM.
  $roles['ADMIN OPCAIM'] = array(
    'name' => 'ADMIN OPCAIM',
    'weight' => 4,
  );

  // Exported role: CABINET COMPTABLE.
  $roles['CABINET COMPTABLE'] = array(
    'name' => 'CABINET COMPTABLE',
    'weight' => 11,
  );

  // Exported role: COLLABORATEUR ENTREPRISE.
  $roles['COLLABORATEUR ENTREPRISE'] = array(
    'name' => 'COLLABORATEUR ENTREPRISE',
    'weight' => 10,
  );

  // Exported role: CONSEILLER ADEFIM.
  $roles['CONSEILLER ADEFIM'] = array(
    'name' => 'CONSEILLER ADEFIM',
    'weight' => 8,
  );

  // Exported role: DIRECTEUR ADEFIM.
  $roles['DIRECTEUR ADEFIM'] = array(
    'name' => 'DIRECTEUR ADEFIM',
    'weight' => 5,
  );

  // Exported role: GESTIONNAIRE ADEFIM.
  $roles['GESTIONNAIRE ADEFIM'] = array(
    'name' => 'GESTIONNAIRE ADEFIM',
    'weight' => 7,
  );

  // Exported role: ORGANISME DE FORMATIONS.
  $roles['ORGANISME DE FORMATIONS'] = array(
    'name' => 'ORGANISME DE FORMATIONS',
    'weight' => 12,
  );

  // Exported role: REFERENT ADEFIM.
  $roles['REFERENT ADEFIM'] = array(
    'name' => 'REFERENT ADEFIM',
    'weight' => 6,
  );

  // Exported role: SUPER ADMIN OPCAIM.
  $roles['SUPER ADMIN OPCAIM'] = array(
    'name' => 'SUPER ADMIN OPCAIM',
    'weight' => 3,
  );

  // Exported role: UTILISATEUR ADEFIM.
  $roles['UTILISATEUR ADEFIM'] = array(
    'name' => 'UTILISATEUR ADEFIM',
    'weight' => 13,
  );

  return $roles;
}
