<?php
/**
 * @file
 * opcaim_roles.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function opcaim_roles_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'Accéder aux reporting'.
  $permissions['Accéder aux reporting'] = array(
    'name' => 'Accéder aux reporting',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Accéder à l’ensemble des données de l’extranet'.
  $permissions['Accéder à l’ensemble des données de l’extranet'] = array(
    'name' => 'Accéder à l’ensemble des données de l’extranet',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Faire une demande Action de formation'.
  $permissions['Faire une demande Action de formation'] = array(
    'name' => 'Faire une demande Action de formation',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Faire une demande contrat de professionnalisation'.
  $permissions['Faire une demande contrat de professionnalisation'] = array(
    'name' => 'Faire une demande contrat de professionnalisation',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer la collecte'.
  $permissions['Gérer la collecte'] = array(
    'name' => 'Gérer la collecte',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes  Gestionnaire ADEFIM et Conseiller ADEFIM'.
  $permissions['Gérer les comptes  Gestionnaire ADEFIM et Conseiller ADEFIM'] = array(
    'name' => 'Gérer les comptes  Gestionnaire ADEFIM et Conseiller ADEFIM',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes  Organisme de formation'.
  $permissions['Gérer les comptes  Organisme de formation'] = array(
    'name' => 'Gérer les comptes  Organisme de formation',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes ADEFIM(Directeur, Référent, ...)'.
  $permissions['Gérer les comptes ADEFIM(Directeur, Référent, ...)'] = array(
    'name' => 'Gérer les comptes ADEFIM(Directeur, Référent, ...)',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes ADMIN OPCAIM'.
  $permissions['Gérer les comptes ADMIN OPCAIM'] = array(
    'name' => 'Gérer les comptes ADMIN OPCAIM',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes Cabinet comptable'.
  $permissions['Gérer les comptes Cabinet comptable'] = array(
    'name' => 'Gérer les comptes Cabinet comptable',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes Référent ADEFIM'.
  $permissions['Gérer les comptes Référent ADEFIM'] = array(
    'name' => 'Gérer les comptes Référent ADEFIM',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes utilisateurs'.
  $permissions['Gérer les comptes utilisateurs'] = array(
    'name' => 'Gérer les comptes utilisateurs',
    'roles' => array(),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les comptes « Collaborateur entreprise » (ainsi que leur rattachement SIRET et leurs droits)'.
  $permissions['Gérer les comptes « Collaborateur entreprise » (ainsi que leur rattachement SIRET et leurs droits)'] = array(
    'name' => 'Gérer les comptes « Collaborateur entreprise » (ainsi que leur rattachement SIRET et leurs droits)',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Gérer les données entreprises (DPC, collecte)'.
  $permissions['Gérer les données entreprises (DPC, collecte)'] = array(
    'name' => 'Gérer les données entreprises (DPC, collecte)',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Modifier les établissements'.
  $permissions['Modifier les établissements'] = array(
    'name' => 'Modifier les établissements',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Suivre les demandes'.
  $permissions['Suivre les demandes'] = array(
    'name' => 'Suivre les demandes',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Suivre les paiements'.
  $permissions['Suivre les paiements'] = array(
    'name' => 'Suivre les paiements',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Supprimer un établissement'.
  $permissions['Supprimer un établissement'] = array(
    'name' => 'Supprimer un établissement',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Valider les demandes de compte ADEFIM'.
  $permissions['Valider les demandes de compte ADEFIM'] = array(
    'name' => 'Valider les demandes de compte ADEFIM',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Valider les demandes de compte Collaborateur entreprise'.
  $permissions['Valider les demandes de compte Collaborateur entreprise'] = array(
    'name' => 'Valider les demandes de compte Collaborateur entreprise',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Valider les demandes de compte Collaborateur entreprise.'.
  $permissions['Valider les demandes de compte Collaborateur entreprise.'] = array(
    'name' => 'Valider les demandes de compte Collaborateur entreprise.',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  // Exported permission: 'Visualiser les salaires des salariés'.
  $permissions['Visualiser les salaires des salariés'] = array(
    'name' => 'Visualiser les salaires des salariés',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'dgf_user_habilitation',
  );

  return $permissions;
}
