<?php

// LANGUES
define('J_INTRO' , "Afin d'étudier votre demande, veuillez joindre les pièces nécessaires à l’instruction");
define('J_INFOS_REQUIRE' , 'Les champs avec un * sont obligatoires');
define('J_INFOS_WARNING' ,  '<b>ATTENTION</b>: la taille maximale des pièces justificatives est limité à 5 Méga Octets');
define('J_INFOS', 'Afin d’étudier votre demande, veuillez joindre les pièces nécessaires à l’instruction.');
define('J_INFOS_PLUS', 'Les pièces non-obligatoires ne conditionnent pas l’instruction ou l’engagement de la demande mais pourront conditionner le paiement.');
define('J_FILE_SELECT' , 'Sélectionnez le type de pièce à joindre');
define('J_FILE_SELECT_REQUIRE' , 'Type de pièce(s) à joindre impérativement');
define('J_FILE_SELECT_COMP' , 'Type de pièces complémentaires éventuelles');
define('J_FILE_FORMAT', 'Merci de joindre vos documents au format: .pdf, .doc, .docx, .xls, .xlsx, .jpeg, .png');
define('J_FILE_BROWSE' , '(parcourir les fichiers de votre ordinateur)');
define('J_FILE_FIND' ,  'Recherche le fichier que vous désirez joindre');
define('J_FILE_CLIC' ,  'Cliquez sur << Joindre la pièce >> ');
define('J_FILE_DEPOT' , 'Votre fichier àété déposé sur le serveur');
define('J_ERROR_MANDATORY', "Pour passer à l'étape suivante, vous devez joindre toutes les pièces impératives.");
