<?php
define('ATT_TITRE', "Certifier les informations de votre demande :");
define('ATT_LABEL', "Je certifie l'exactitude des renseignements fournis, et m'engage à signer le présent contrat, et à
    avertir l'OPCAIM de toutes modifications relatives à celui-ci");
define('ATT_MSG_MERCI', "Nous vous remercions d'avoir utilisé l'extranet, votre demande sera examiné dans les plus
    brefs délais");
define('ATT_BOUTON', "Transmettre ma demande");

define('ATT_ERR_CERTIFIE', "Vous devez cocher la case pour continuer.");
define('ATT_ERR_ADEFIM', "Veuillez sélectionner une ADEFIM pour continuer.");

define('MSG_FIN_DE_SAISIE','Message de fin de saisie à définir');
define('MSG_FIN_DE_SAISIE_BUTTON_EDIT_CERFA', 'Editer le CERFA');
define('MSG_FIN_DE_SAISIE_BUTTON_FUNDING_REQUEST', 'Réaliser une demande de financement de la formation');
define('MSG_FIN_DE_SAISIE_BUTTON_NEW_REQUEST', 'Réaliser une autre demande');
define('MSG_FIN_DE_SAISIE_BUTTON_QUIT', "Revenir à l'accueil");