<?php

// define('DB_EXTRANET', 'opcaim_extranet');
// define('DB_SLAVE', 'opcaim_referentiel_esclave');

define('ERR_STD_ESTABL_MANAG_SIRET', 'le champ SIRET est obligatoire.');
define('ERR_STD_ESTABL_MANAG_NUMBER_STREET', 'le champ numéro de rue est obligatoire.');
define('ERR_STD_ESTABL_MANAG_NAME_STREET', 'le champ nom de rue est obligatoire.');
define('ERR_STD_ESTABL_MANAG_COMPLEMENT_ADRESS', 'le champ complément d\'adresse est obligatoire.');
define('ERR_STD_ESTABL_MANAG_CITY', 'le champ ville est obligatoire.');
define('ERR_STD_ESTABL_MANAG_NAF', 'le champ code NAF est obligatoire.');
define('ERR_STD_ESTABL_MANAG_CORP_NAME', 'le champ raison siociale est obligatoire.');
define('ERR_STD_ESTABL_MANAG_ZIP', 'le champ code postal est obligatoire.');
define('ERR_STD_ESTABL_MANAG_PHONE', 'le champ téléphone est obligatoire.');
define('ERR_STD_ESTABL_MANAG_NACE', 'le champ code NACE est obligatoire.');
define('ERR_STD_ESTABL_MANAG_TITLE', 'le champ titre est obligatoire.');
define('ERR_STD_ESTABL_MANAG_FIRTSNAME', 'le champ prénom est obligatoire.');
define('ERR_STD_ESTABL_MANAG_EMAIL', 'le champ est courriel obligatoire.');
define('ERR_STD_ESTABL_MANAG_LASTNAME', 'le champ nom est obligatoire.');
define('ERR_STD_ESTABL_MANAG_FUNCTION', 'le champ fonction est obligatoire.');
define('ERR_STD_ESTABL_MANAG_CONFIRM', 'le champ confirmation courriel est obligatoire.');

define('ERR_SPE_ESTABL_MANAG_CONFIRM', 'le champ courriel et confirmation courriel doivent être identique.');
define('ERR_SPE_ESTABL_MANAG_SIRET_KO', 'Le SIRET n\'est pas valide (clé non conforme).');
define('ERR_SPE_ESTABL_MANAG_SIRET_FOUND', 'L\'établissement a déjà été trouvé pour ce SIRET.');
