<?php
// Messages standard
define('MSG_MESSAGE_INFORMATION_FINAL',
'<p>Le financement de l\'Opcaim est subordonné à la constitution du dossier dans les délais fixés et à la validation du contrat par la Dirrecte</p>
			<p>Les pièces justifiactives doivent être adressées à l\'Opcaim <b>au plus tard et impérativement dans les 5 jours ouvrables qui suivent le début du contrat</b></p>
			<p>Respect des obligations d\'informations CE</p>
			<p><b>Toute modification des éléments saisies dans l\'Extranet peut entrainer une révision du finanacement accordé</b></p>');

define('MSG_MESSAGE_INFORMATION_FINAL_BUTTON', 'Visualiser le CERFA et finaliser la demande');