<?php

define('ERR_STD_ESTABL_VALID_SIRET', 'le champ SIRET est obligatoire.');
define('ERR_STD_ESTABL_VALID_NUMBER_STREET', 'le champ numéro de rue est obligatoire.');
define('ERR_STD_ESTABL_VALID_NAME_STREET', 'le champ nom de rue est obligatoire.');
define('ERR_STD_ESTABL_VALID_COMPLEMENT_ADRESS', 'le champ complément d\'adresse est obligatoire.');
define('ERR_STD_ESTABL_VALID_CITY', 'le champ ville est obligatoire.');
define('ERR_STD_ESTABL_VALID_NAF', 'Veuillez sélectionner un code NAF.');
define('ERR_STD_ESTABL_VALID_CORP_NAME', 'le champ raison siociale est obligatoire.');
define('ERR_STD_ESTABL_VALID_ZIP', 'le champ code postal est obligatoire.');
define('ERR_STD_ESTABL_VALID_PHONE', 'le champ téléphone est obligatoire.');
define('ERR_STD_ESTABL_VALID_NACE', 'le champ code NACE est obligatoire.');
define('ERR_STD_ESTABL_VALID_TITLE', 'Veuillez sélectionner un titre.');
define('ERR_STD_ESTABL_VALID_FIRTSNAME', 'le champ prénom est obligatoire.');
define('ERR_STD_ESTABL_VALID_EMAIL', 'le champ est courriel obligatoire.');
define('ERR_STD_ESTABL_VALID_LASTNAME', 'le champ nom est obligatoire.');
define('ERR_STD_ESTABL_VALID_FUNCTION', 'le champ fonction est obligatoire.');
define('ERR_STD_ESTABL_VALID_CONFIRM', 'le champ confirmation courriel est obligatoire.');

define('ERR_SPE_ESTABL_VALID_CONFIRM', 'le champ courriel et confirmation courriel doivent être identique.');
define('ERR_SPE_ESTABL_VALID_SIRET_KO', 'Le SIRET n\'est pas valide (clé non conforme).');
define('ERR_SPE_ESTABL_VALID_SIRET_FOUND', 'L\'établissement a déjà été trouvé pour ce SIRET.');
