<?php

// Defines.
define('LOGIN_MODULE_PATH', drupal_get_path('module', 'login'));

function login_menu() {
  $items = array();
  $items['login'] = array(
      'title' => t('Se connecter'),
      'page callback' => 'login_view',
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * @param array $form
 * @param array $form_state
 */
function login_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (arg(0) == 'user' && arg(1) == 'reset' && !user_is_logged_in()) {
    $form['#after_build'] = array('login_reset_password_custom');
  }
}

/**
 * @param array $form_element
 * @param array $form_state
 * @return array $form_element
 */
function login_reset_password_custom($form_element, &$form_state) {
  $form_element['locale']['#access'] = false;
  $form_element['account']['mail']['#access'] = false;
  $form_element['timezone']['#access'] = false;
  $form_state['redirect'] = 'dashboard';

  return $form_element;
}

/*
 * Implementation of hook_theme().
*/
function login_theme($existing, $type, $theme, $path) {
  return array(
    // Template général pour afficher la médiathèque
    'login_theme' => array(
        'variables' => array(
            'error' => null,
        ),
        'render element' => 'element',
        'template' => 'login',
        'path' => drupal_get_path('module', 'login') .'/theme',
    ),
  );
}

function login_view() {
  global $user;

  drupal_add_css(LOGIN_MODULE_PATH . '/css/general.css');
  drupal_add_css(LOGIN_MODULE_PATH . '/css/login.css');
  drupal_add_css(LOGIN_MODULE_PATH . '/css/poppins.css');
  drupal_add_js(LOGIN_MODULE_PATH . '/js/login.js');

  require_once 'login_langs.inc';
  require_once 'login_form.inc';
  require_once 'login_form_submit.inc';
  require_once 'login_db.inc';

  // Si l'utilisateur est déjà connecté, il est redirigé vers sa page d'accueil
  if ($user->uid != 0) {
    drupal_goto('dashboard');
  }

  // Si on est post, c'est que l'utilisateur tente de se connecter.
  if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($_POST['form_id'] === 'login_form') {
      check_login();
    } else if ($_POST['form_id'] === 'login_password_forgot_form') {
      password_forgot();
    } else if ($_POST['form_id'] === 'login_follow_form') {
      follow_login();
    }

  }

  $variables =  array(
    'login_form' => drupal_get_form('login_form'),
    'login_password_forgot_form' => drupal_get_form('login_password_forgot_form'),
    'login_follow_form' => drupal_get_form('login_follow_form')
  );

  $output = theme('login_theme', $variables);

  return $output;
}

function login_user_presave(&$edit, $account, $category) {
  if (!isset($edit['data']['extranet_user'])) {
    $edit['data']['extranet_user'] = new stdClass();
  }
  if (isset($edit['extranet_user']['drupal_user'])) {
    $edit['data']['extranet_user']->drupal_user = $edit['extranet_user']['drupal_user'];
  }
  if (isset($edit['extranet_user']['user_entreprise'])) {
    $edit['data']['extranet_user']->user_entreprise = $edit['extranet_user']['user_entreprise'];
  }
  if (isset($edit['extranet_user']['user_adefim'])) {
    $edit['data']['extranet_user']->user_adefim = $edit['extranet_user']['user_adefim'];
  }
  if (isset($edit['extranet_user']['user_autre'])) {
    $edit['data']['extranet_user']->user_autre = $edit['extranet_user']['user_autre'];
  }
  if (isset($edit['extranet_user']['user_organisme_formation'])) {
    $edit['data']['extranet_user']->user_organisme_formation = $edit['extranet_user']['user_organisme_formation'];
  }
  if (isset($edit['extranet_user']['habilitations'])) {
    $edit['data']['extranet_user']->habilitations = $edit['extranet_user']['habilitations'];
  }
  if (isset($edit['extranet_user']['entreprises'])) {
    $edit['data']['extranet_user']->entreprises = $edit['extranet_user']['entreprises'];
  }
}