<?php

define('ESPACE_DEDIE', "Votre espace dédié");

define('TEXTE_BOUTON_1', "Vous souhaitez créer");
define('TEXTE_BOUTON_LIEN_1', "un compte utilisateur");
define('TEXTE_BOUTON_2', "Vous avez oublié");
define('TEXTE_BOUTON_LIEN_2', "votre mot de passe");
define('TEXTE_BOUTON_3', "Vous souhaitez suivre");
define('TEXTE_BOUTON_LIEN_3', "votre demande<br>de création de compte");

define('ERROR_CHECK_LOGIN_1', "L'identifiant saisi n’est pas reconnu.");
define('ERROR_CHECK_LOGIN_2', "Le mot de passe ne correspond pas à l’identifiant saisi.");
define('ERROR_CHECK_LOGIN_REQUIRE_COMPTE', 'Le champ "Votre compte" est obligatoire.');
define('ERROR_CHECK_LOGIN_REQUIRE_PASSWORD', 'Le champ "Votre mot de passe" est obligatoire.');

define('MODAL_FORGOT_PWD_TITRE', 'Vous avez oublié <span class="subtitle orange">votre mot de passe</span>');
define('MODAL_FORGOT_PWD_CONTENT','Veuillez saisir votre adresse e-mail pour réinitialiser votre mot de passe. <div class="help">Un lien de modification de mot de passe vous sera envoyé automatiquement sur votre e-mail.</div>');

define('FORGOT_PWD_VALID', 'Un email vous a été envoyé pour réinitialiser votre mot de passe');

define('ERROR_FORGOT_PWD_MAIL_EMPTY', 'Le champ "email" est obligatoire.');
define('ERROR_FORGOT_PWD_MAIL_KO', "Aucun compte n'est associé à cette adresse e-mail, veuillez vérifier les informations saisies ou faire une demande de compte.");

define('MODAL_FOLLOW_LOGIN_TITRE', 'Vous souhaitez suivre <span class="subtitle orange">votre demande de création de compte</span>');
define('MODAL_FOLLOW_LOGIN_CONTENT', "Veuillez saisir le numéro de la demande et l'adresse email du compte utilisateur pour suivre votre demande.");

define('ERROR_FOLLOW_LOGIN_NUMERO_EMPTY', 'Le champ "numéro de demande" est obligatoire.');
define('ERROR_FOLLOW_LOGIN_EMAIL_EMPTY', 'Le champ "email" est obligatoire.');
